myVars = DomesticFuelCostsFinal.Properties.VariableNames;
myVars = myVars';
hold on

plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PeatBriquettesBaled);
hold on
plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.CoalNuggets);
plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PremiumCoalbulk);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PremiumCoalbag);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.StandardCoalbulk);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.StandardCoalbag);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.StandardAnthracite);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.GradeAAnthracite);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.OvoidsLowSmokebulk);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.OvoidsLowSmokebag);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.GasOilschedule);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.GasOildiscounted);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.Keroseneschedule);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.Kerosenediscounted);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.BulkLPG);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.BottledButane);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.BottledPropane34kg);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.BottledPropane47kg);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesGasBandD120GJperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesGasBandD220200GJperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesGasBandD3200GJperannum);
   % plot(DomesticFuelCostsFinal.PriceDirectivesElectricityBandDA1000kWhperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesElectricityBandDB10002500kWhperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesElectricityBandDC25005000kWhperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesElectricityBandDD500015000kWhperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.PriceDirectivesElectricityBandDE15000kWhperannum);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.WoodPelletsBulkDelivery);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.WoodPelletsbagged);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.WoodBriquettes);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.HardwoodSmallBag02moistureCollected);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.SoftwoodSmallBag025moistureCollected);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.HardwoodFullPallet02moistureDelivered);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.SoftwoodFullPallet025moistureDelivered);
    plot(DomesticFuelCostsFinal.Date, DomesticFuelCostsFinal.SoftwoodBulkloose025moistureDelivered);
legend('PeatBriquettesBaled',...
    'CoalNuggets',...
    'PremiumCoalbulk',...
    'PremiumCoalbag',...
    'StandardCoalbulk',...
    'StandardCoalbag',...
    'StandardAnthracite',...
    'GradeAAnthracite',...
    'OvoidsLowSmokebulk',...
    'OvoidsLowSmokebag',...
    'GasOilschedule',...
    'GasOildiscounted',...
    'Keroseneschedule',...
    'Kerosenediscounted',...
    'BulkLPG',...
    'BottledButane',...
    'BottledPropane34kg',...
    'BottledPropane47kg',...
    'PriceDirectivesGasBandD120GJperannum',...
    'PriceDirectivesGasBandD220200GJperannum',...
    'PriceDirectivesGasBandD3200GJperannum',...
    'PriceDirectivesElectricityBandDA1000kWhperannum',...
    'PriceDirectivesElectricityBandDB10002500kWhperannum',...
    'PriceDirectivesElectricityBandDC25005000kWhperannum',...
    'PriceDirectivesElectricityBandDD500015000kWhperannum',...
    'PriceDirectivesElectricityBandDE15000kWhperannum',...
    'WoodPelletsBulkDelivery',...
    'WoodPelletsbagged',...
    'WoodBriquettes',...
    'HardwoodSmallBag02moistureCollected',...
    'SoftwoodSmallBag025moistureCollected',...
    'HardwoodFullPallet02moistureDelivered',...
    'SoftwoodFullPallet025moistureDelivered',...
    'SoftwoodBulkloose025moistureDelivered')
